[package]
name = "shredder_demo"
version = "0.1.0"
edition = "2021"

[dependencies]
# Para desensamblar y re-ensamblar c√≥digo x64
iced-x86 = "1.21.0"
# Para leer/escribir archivos PE (.exe)
exe = "0.5"
# Error handling
thiserror = "1"
rand = "0.9.2"
